services:

    app.form.type.imagepreview:
        class: AppBundle\Form\Type\ImagePreviewType
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: imagepreview }

    app.admin.portfolio_category:
        class: AppBundle\Admin\PortfolioCategoryAdmin
        arguments: [~, AppBundle\Entity\PortfolioCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: portfolio, label: Categories }

    app.admin.portfolio_client:
        class: AppBundle\Admin\PortfolioClientAdmin
        arguments: [~, AppBundle\Entity\PortfolioClient, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: portfolio, label: Clients }

    app.admin.portfolio_image:
        class: AppBundle\Admin\PortfolioImageAdmin
        arguments: [~, AppBundle\Entity\PortfolioImage, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: portfolio, label: Images }

    app.admin.portfolio_item:
        class: AppBundle\Admin\PortfolioItemAdmin
        arguments: [~, AppBundle\Entity\PortfolioItem, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: portfolio, label: Items }

    app.portfolio_item.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\PortfolioItem

    app.portfolio_item.service:
        class: AppBundle\Services\PortfolioItemService
        arguments:
            - "@app.portfolio_item.repository"
